### ISSUE TITLE
Wrong Bash override

### ISSUE THREAD

**Issue by HollayHorvath** [antalmiklos/terminalfailbot#1]
The line `echo 'function command_not_found_handle() {python3 $HOME/repos/terminalfailbot/terminalfail.py "$@"}' >> ~/.bashrc` is not a valid Bash command, it should be `echo 'function command_not_found_handle() { python3 $HOME/repos/terminalfailbot/terminalfail.py "$@" ; }' >> ~/.bashrc`

**Comment by antalmiklos** [comment]
Big true, thx
